name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8.0.322+6'
          distribution: 'adopt'
      - name: Run Maven verify
        run: mvn clean verify -PmavenCentral
